# Generated by Django 5.2 on 2025-05-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photohub', '0002_photo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
